version: '3'
services:
  db: 
    image: postgres:9.6
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432